### ISSUE TITLE
Design Mint.com

### ISSUE THREAD

**Issue by linhe0x0** [xitu/system-design-primer#14]
- Markdown: [solutions/system_design/mint/README.md](https://github.com/xitu/system-design-primer/blob/master/solutions/system_design/mint/README.md)
- 翻译积分：6

**Comment by whatbeg** [comment]
@sqrthree 认领翻译，6天内完成行不？

**Comment by linhe0x0** [comment]
可以~

**Comment by lsvih** [comment]
。。晚了一步哈哈哈

**Comment by whatbeg** [comment]
@sqrthree 翻译完成，PR #35
