### ISSUE TITLE
设计 Pastebin.com（或 Bit.ly）

### ISSUE THREAD

**Issue by linhe0x0** [xitu/system-design-primer#15]
- Markdown: [solutions/system_design/pastebin/README.md](https://github.com/xitu/system-design-primer/blob/master/solutions//system_design/pastebin/README.md)
- 翻译积分：4
- PR: #34

**Comment by whatbeg** [comment]
申请翻译

**Comment by lsvih** [comment]
认领翻译 @sqrthree

**Comment by linhe0x0** [comment]
好哒
