### ISSUE TITLE
设计一个键-值缓存来存储最近 web 服务查询的结果

### ISSUE THREAD

**Issue by linhe0x0** [xitu/system-design-primer#16]
- Markdown: [solutions/system_design/query_cache/README.md](https://github.com/xitu/system-design-primer/blob/master/solutions/system_design/query_cache/README.md)
- Review：#27
- 翻译积分：4

**Comment by lsvih** [comment]
申请翻译

**Comment by linhe0x0** [comment]
好哒

**Comment by lsvih** [comment]
@sqrthree  请问文中指向英文原文的链接是否要换成中文文档的？

**Comment by linhe0x0** [comment]
是的~

**Comment by xunge0613** [comment]
@sqrthree 窝一边参考这篇翻译我的那篇，一边校对可好……？

**Comment by linhe0x0** [comment]
好的

**Comment by linhe0x0** [comment]
@xunge0613 You can review it at #23

**Comment by lsvih** [comment]
@xunge0613 pr 的分支改了，现在您可以在 #27 进行 review

**Comment by xunge0613** [comment]
收到~~ 预计明晚 review完毕~
