### ISSUE TITLE
在 AWS 上设计支持百万级到千万级用户的系统

### ISSUE THREAD

**Issue by linhe0x0** [xitu/system-design-primer#18]
- Markdown: [solutions/system_design/scaling_aws/README.md](https://github.com/xitu/system-design-primer/blob/master/solutions/system_design/scaling_aws/README.md)
- PR: #31
- 翻译积分：7

**Comment by AceLeeWinnie** [comment]
认领

**Comment by linhe0x0** [comment]
好哒

**Comment by AceLeeWinnie** [comment]
#31 翻译完成，求校对

**Comment by 0x4ec7** [comment]
校对认领

**Comment by linhe0x0** [comment]
@0x4ec7 好的，地址在 #31 _(:з」∠)_ 差点都忘了这个了
