### ISSUE TITLE
为社交网络设计数据结构

### ISSUE THREAD

**Issue by linhe0x0** [xitu/system-design-primer#19]
- Markdown: [solutions/system_design/social_graph/README.md](https://github.com/xitu/system-design-primer/blob/master/solutions/system_design/social_graph/README.md)
- 翻译积分：4 分
- PR: #33

**Comment by AceLeeWinnie** [comment]
@sqrthree 认领

**Comment by linhe0x0** [comment]
好哒

**Comment by AceLeeWinnie** [comment]
咦，这个不算积分么

**Comment by linhe0x0** [comment]
遗忘了，我正在陆续添加。

**Comment by AceLeeWinnie** [comment]
好哒，上次翻了一篇没加上

**Comment by linhe0x0** [comment]
已经更新好啦
