### ISSUE TITLE
Design the Twitter timeline and search

### ISSUE THREAD

**Issue by linhe0x0** [xitu/system-design-primer#20]
- Markdown: [solutions/system_design/twitter/README.md](https://github.com/xitu/system-design-primer/blob/master/solutions/system_design/twitter/README.md)
- 翻译积分：6

**Comment by Airmacho** [comment]
认领，顺便根据每个难度，长度请把翻译天数，积分也标识下？

**Comment by Airmacho** [comment]
I really love Twitter

**Comment by linhe0x0** [comment]
好哒~ 这个项目时间上要求不是太紧急，自己把握下，尽快就好啦，积分我忙完了再来加吧😂

**Comment by leviding** [comment]
@Airmacho 亲，这篇翻译怎么样了

**Comment by leviding** [comment]
@Airmacho 是否继续翻译呢？如果有时间的话，六天内能完成吗？

**Comment by leviding** [comment]
文章释放，等待新译者。

**Comment by jingzhilehuakai** [comment]
翻译认领

**Comment by leviding** [comment]
@jingzhilehuakai 好的呢

**Comment by leviding** [comment]
@jingzhilehuakai 翻译的怎么样了？

**Comment by jingzhilehuakai** [comment]
@leviding 抱歉，只翻译了一点点，就遇到棘手的事情，一直忙着，才上 GitHub 看到你的消息，文章释放吧，我估计得再忙一段时间，才有时间翻译。耽误了文章的翻译时间，很是抱歉😞

**Comment by leviding** [comment]
释放，等待新译者

**Comment by HydeSong** [comment]
真的那么难翻译么

**Comment by lsvih** [comment]
翻译认领

**Comment by leviding** [comment]
@lsvih 好的呢

**Comment by lsvih** [comment]
@leviding 完成

**Comment by leviding** [comment]
@lsvih Great！
