### ISSUE TITLE
Design a web crawler

### ISSUE THREAD

**Issue by linhe0x0** [xitu/system-design-primer#21]
- Markdown: [solutions/system_design/web_crawler/README.md](https://github.com/xitu/system-design-primer/blob/master/solutions/system_design/web_crawler/README.md)
- PR：#28
- 翻译积分：5

**Comment by xunge0613** [comment]
申请翻译~ 五一节可以充实地度过了 =。= @sqrthree

**Comment by linhe0x0** [comment]
好哒

**Comment by xunge0613** [comment]
对啦 想请问一下，如果图片上有英文的话，需要把英文 P 成中文咩？
https://camo.githubusercontent.com/379e7661ccfd4303985ca8b90f1ce7e9e664d3ab/687474703a2f2f692e696d6775722e636f6d2f786a64414155762e706e67

**Comment by xunge0613** [comment]
主页的 md 里面
Step 2: Create a high level design
建议翻译成 
第二步：创建一个高层次设计

参考： http://dict.youdao.com/w/%E9%AB%98%E5%B1%82%E6%AC%A1%E8%AE%BE%E8%AE%A1/

此处 high level 的含义应该和底层相对吧……
以及我在翻译过程中遇到了一处有上下文的
Only sketch high level components and interactions for this use case, no need to go into depth

此处翻译为高级感觉不妥……

**Comment by xunge0613** [comment]
https://github.com/xitu/system-design-primer/blob/master/README-zh-Hans.md#信封背面的计算

Back-of-the-envelope calculations
这个词我在 http://dict.youdao.com/w/eng/%E9%80%9A%E8%BF%87%E4%B8%80%E9%A1%B9%E5%B0%81%E5%BA%95%E8%AE%A1%E7%AE%97/ 以及 http://cn.bing.com/dict/back-of-the-envelope%20calculation
上面看有一些是译为 封底计算，有一些就译为 粗略的估算…… 感觉有待斟酌？

**Comment by linhe0x0** [comment]
图片是通过 OmniGraffle 软件制作的，如果你有这个软件的话，repo 里有源文件，可以直接翻译，如果没有的话，就先暂时搁置吧，我再想想办法。

**Comment by xunge0613** [comment]
然而…… 并没有 mac ……
